### ISSUE TITLE
Put html template & css in it's own file

### ISSUE THREAD

**Issue by blazeu** [coala/gci-leaders#21]

**Comment by jayvdb** [comment]
[GitMate.io](https://gitmate.io) thinks the label prediction failed because there are not enough labels. Three labels must have been set on at least three issues each.

The contributor prediction failed because there are not enough contributors. Three contributors must have authored comments on at least three issues each.

**Comment by blazeu** [comment]
.js is will be done in https://github.com/coala/gci-leaders/pull/19
