### ISSUE TITLE
Manually fix Github usernames?

### ISSUE THREAD

**Issue by ghost** [coala/gci-leaders#97]
Hey, I'm one of the current leaders for MetaBrainz. My github account is linked as "eshansingh", but I recently changed my username to "naiveaiguy". Is there a way I can manually correct this in a PR?

**Comment by blazeu** [comment]
"Manually", no.

But if you can find a way to "fix" or link the rest of non linked participants automatically, sure.

This is how our "guessing" of GitHub username currently work https://github.com/coala/gci-leaders/pull/62 & https://github.com/coala/gci-leaders/pull/74 & https://github.com/coala/gci-leaders/pull/75

There was a issue made because of you specifically https://github.com/coala/gci-leaders/issues/93
but the patch did not work expectedly to remove your old GitHub link.

**Comment by blazeu** [comment]
As per https://github.com/coala/gci-leaders/pull/75

I think you just need to set your organization as public under your profile.

Might need some time because https://github.com/coala/gci-leaders/issues/93 is not fully fixed yet ;)

**Comment by ghost** [comment]
Oh, I'm terribly sorry if I caused trouble >.< For MetaBrainz you don't actually join the org, so I can't set it as public. I'll close this for now.

**Comment by ghost** [comment]
It appears my GitHub is now gone. Looking through the code right now to see if I can fix this.

**Comment by andrewda** [comment]
@naiveaiguy Yea, there's no way to find it at the moment. The fix username caching PR was just to remove your 404ing username. We'll need to implement new methods to find your new username. See #100.
